# Generated by Django 4.1.4 on 2023-01-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('code', models.PositiveSmallIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('directory', models.CharField(max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
