# Generated by Django 4.1.4 on 2023-01-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_image', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
                ('sort_order', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('categories_status', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.PositiveSmallIntegerField()),
                ('categories_name', models.CharField(max_length=255)),
                ('categories_heading_title', models.CharField(max_length=255)),
                ('categories_description', models.TextField()),
                ('categories_meta_title', models.CharField(max_length=255)),
                ('categories_meta_description', models.TextField()),
                ('categories_meta_keywords', models.CharField(max_length=255)),
                ('categories_seo_url', models.CharField(max_length=255)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
        ),
    ]
